services:
  db:
    image: postgres:15
    container_name: eda_analysis_container
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: root
      POSTGRES_DB: EdaAnalysis
    ports:
      - "5432:5432"
    volumes:
      - ./datasets:/datasets  # map the datasets directory to the container